// <auto-generated />
namespace Firoozi.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mari : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mari));
        
        string IMigrationMetadata.Id
        {
            get { return "201901091907331_mari"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
